Repository Integrator-group-5/backend, pull requests merged in 2024-11, with the labels that each got.

#2 Tineo - Security and User Management Implementation
  Luxury Wear.postman_collection.json
  README.md
  pom.xml
  src/main/java/com/luxury/wear/service/controller/UserController.java
  src/main/java/com/luxury/wear/service/dto/EmailRequest.java
  src/main/java/com/luxury/wear/service/entity/User.java
  src/main/java/com/luxury/wear/service/exception/EntityAlreadyExistsException.java
  src/main/java/com/luxury/wear/service/exception/GlobalExceptionHandler.java
  src/main/java/com/luxury/wear/service/repository/UserRepository.java
  src/main/java/com/luxury/wear/service/roles/UserRole.java
  src/main/java/com/luxury/wear/service/security/PasswordEncoder.java
  src/main/java/com/luxury/wear/service/security/SecurityConfig.java
  src/main/java/com/luxury/wear/service/service/user/UserService.java
  src/main/java/com/luxury/wear/service/service/user/UserServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: enhancement

#4 Product by category endpoint
  Luxury Wear.postman_collection.json
  src/main/java/com/luxury/wear/service/controller/ProductController.java
  src/main/java/com/luxury/wear/service/repository/ProductRepository.java
  src/main/java/com/luxury/wear/service/security/JwtAuthenticationFilter.java
  src/main/java/com/luxury/wear/service/security/SecurityConfig.java
  src/main/java/com/luxury/wear/service/service/product/ProductService.java
  src/main/java/com/luxury/wear/service/service/product/ProductServiceImpl.java
Labels: enhancement

#5 Admin permissions endpoint
  Luxury Wear.postman_collection.json
  src/main/java/com/luxury/wear/service/controller/UserController.java
  src/main/java/com/luxury/wear/service/security/SecurityConfig.java
  src/main/java/com/luxury/wear/service/service/user/UserService.java
  src/main/java/com/luxury/wear/service/service/user/UserServiceImpl.java
Labels: enhancement

#6 Define category endpoint
  Luxury Wear.postman_collection.json
  src/main/java/com/luxury/wear/service/controller/CategoryController.java
  src/main/java/com/luxury/wear/service/entity/Category.java
  src/main/java/com/luxury/wear/service/entity/Cover.java
  src/main/java/com/luxury/wear/service/security/JwtAuthenticationFilter.java
  src/main/java/com/luxury/wear/service/security/SecurityConfig.java
  src/main/java/com/luxury/wear/service/service/category/CategoryService.java
  src/main/java/com/luxury/wear/service/service/category/CategoryServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: documentation, enhancement

#7 Post products
  Luxury Wear.postman_collection.json
  src/main/java/com/luxury/wear/service/commons/Constants.java
  src/main/java/com/luxury/wear/service/entity/Product.java
  src/main/java/com/luxury/wear/service/repository/ProductRepository.java
  src/main/java/com/luxury/wear/service/service/product/ProductServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: documentation, enhancement

#11 Category products
  src/main/java/com/luxury/wear/service/entity/Category.java
  src/main/java/com/luxury/wear/service/entity/Product.java
  src/main/java/com/luxury/wear/service/repository/ProductRepository.java
  src/main/java/com/luxury/wear/service/service/product/ProductServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: enhancement

#12 Swagger docs
  src/main/java/com/luxury/wear/service/controller/CategoryController.java
  src/main/java/com/luxury/wear/service/controller/ProductController.java
  src/main/java/com/luxury/wear/service/controller/SizeController.java
  src/main/java/com/luxury/wear/service/controller/UserController.java
Labels: documentation

#14 Update product size management
  src/main/java/com/luxury/wear/service/commons/Constants.java
  src/main/java/com/luxury/wear/service/controller/ProductController.java
  src/main/java/com/luxury/wear/service/entity/Product.java
  src/main/java/com/luxury/wear/service/service/product/ProductServiceImpl.java
  src/main/java/com/luxury/wear/service/service/size/SizeService.java
  src/main/java/com/luxury/wear/service/service/size/SizeServiceImpl.java
Labels: documentation, enhancement

#16 Add product soft delete
  src/main/java/com/luxury/wear/service/entity/Product.java
  src/main/java/com/luxury/wear/service/repository/ProductRepository.java
  src/main/java/com/luxury/wear/service/repository/UserRepository.java
  src/main/java/com/luxury/wear/service/service/product/ProductServiceImpl.java
  src/main/resources/data.sql
  src/main/resources/schema.sql
Labels: enhancement
